// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeaxyjID_GS1Zrwqe1ebpA9yNoPqrqNEA',
    appId: '1:11726000711:android:6f6a648ce719faca071762',
    messagingSenderId: '11726000711',
    projectId: 'pingme-7539a',
    databaseURL: 'https://pingme-7539a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pingme-7539a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJDTOyInVQ1sgsJkxk5JkwTE7DVV5RFiE',
    appId: '1:11726000711:ios:73166aa0a19f939b071762',
    messagingSenderId: '11726000711',
    projectId: 'pingme-7539a',
    databaseURL: 'https://pingme-7539a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pingme-7539a.firebasestorage.app',
    iosBundleId: 'com.example.pingme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJDTOyInVQ1sgsJkxk5JkwTE7DVV5RFiE',
    appId: '1:11726000711:ios:73166aa0a19f939b071762',
    messagingSenderId: '11726000711',
    projectId: 'pingme-7539a',
    databaseURL: 'https://pingme-7539a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pingme-7539a.firebasestorage.app',
    iosBundleId: 'com.example.pingme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzKPBNoGs0gjSc_ziJ8w_aMmTYP7UM-yc',
    appId: '1:11726000711:web:f8d02c5f60dbab07071762',
    messagingSenderId: '11726000711',
    projectId: 'pingme-7539a',
    authDomain: 'pingme-7539a.firebaseapp.com',
    databaseURL: 'https://pingme-7539a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pingme-7539a.firebasestorage.app',
  );

}